config/routes.rb
Journal2::Application.routes.draw do
  get "admin/index"
  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	delete 'logout' => :destroy
  end
  get "sessions/create"
  get "sessions/destroy"
  resources :teachers

  resources :misses

  get "pairs/choose_group"
  get "pairs/choose_subject"
  get "admin/choose_subject"
  get "admin/choose_group"
  post "pairs/choose_group"
  post "pairs/choose_subject" 
  resources :pairs
  get "subjects/student_statistics"

  resources :students

  resources :groups

  resources :subjects
	
  resources :main

  

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :students
	has_many :pairs
	has_and_belongs_to_many :subjects
end

app/models/miss.rb
class Miss < ActiveRecord::Base
  belongs_to :student
end

app/models/pair.rb
class Pair < ActiveRecord::Base
	belongs_to :teacher
	belongs_to :subject
	belongs_to :group
	has_many :misses
end

app/models/student.rb
class Student < ActiveRecord::Base	
	belongs_to :group
	has_many :misses
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_and_belongs_to_many :groups
	has_many :pairs
	has_and_belongs_to_many :teachers
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	validates :login, presence: true, uniqueness: true
	has_secure_password
	has_and_belongs_to_many :subjects
	has_many :pairs
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
	@teacher=Teacher.find(session[:teacher_id])
	@subjects=@teacher.subjects
	@groups=Array.new
	@subjects.each do |subject|
		@groups.concat(subject.groups.to_a)
	end
  end

  def logout
	session.destroy
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index,:show]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @all_subjs=all_subjects
    @summary=@all_subjs.inject(0) { |sum,tuple| sum+=tuple[1]}
    @all_subjs.each do |tuple|
      tuple[1]=Float(tuple[1])/@summary
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
	subj_ids=params[:subject_ids]
	subj_ids.each do |subj_id|
		s=Subject.find(subj_id)
		s.groups << @group
	end
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
	subj_ids=params[:subject_ids]
	@group.subjects.clear
	subj_ids.each do |subj_id|
		s=Subject.find(subj_id)
		s.groups << @group
	end
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  def all_subjects
      @all_subjs = Hash.new
      @group.subjects.each do |subj|
        @all_subjs[subj.title]=0;
      end
      Pair.where("group_id = #{@group.id}").each do |pair|
          @all_subjs[pair.subject.title]+=2
      end
      @all_subjs.sort_by {|k,v| -v}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :course, :number_of_students)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	skip_before_action :authorize, [:index]
	def self.get_top_misses
		@top_misses = Hash.new;
		Student.all.each do |student|
			@top_misses["#{student.name + " " + student.surname}"] = 0
			student.misses.each do |miss|
				pair=Pair.find(miss.pair_id)
				if pair.today > Date.today - 7
					if miss.hours != nil
						@top_misses["#{student.name + " " + student.surname}"] += miss.hours
					end
				end
			end
		end
		@top=@top_misses.sort_by {|k, v| -v}.first 5 
	end
	def self.top_missed_subject
		@top_subj= Hash.new
		Subject.all.each do |subject|
			@top_subj["#{subject.title}"] = [0,0]
			subject.pairs.where("today > #{Date.today - 30}").each do |pair|
				pair.misses.each do |miss|
					if miss.hours != nil
						@top_subj["#{subject.title}"][0] += miss.hours
					end
				end
			end
		end
		@top_subj=@top_subj.sort_by{ |k, v| -v[0]}.first 7
	end

	def self.get_pairs_today
		@number=0
		Pair.all.each do |pair|
			if (pair.today > Date.today - 7)
				@number+=1
			end
		end
		return @number
	end

	def self.middle_pairs
		@result=Hash.new
		Pair.all.each do |pair|
			@result[pair.today]=1;
		end
		Pair.all.count/@result.length.to_f
	end
	def self.max_pairs
		@max=0
		Teacher.all.each do |teacher|
			tmp = teacher.pairs.count
			if(tmp > @max)
				@max = tmp 
			end
		end
		return @max
	end
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  before_action :set_pair, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:show,:index]

  # GET /pairs
  # GET /pairs.json
  def index
    @pairs = Pair.all
  end

  # GET /pairs/1
  # GET /pairs/1.json
  def show
  end

  # GET /pairs/new
  def new
	@subj=Subject.find(params[:subject_id])
	@group=Group.find(params[:group_id])
	@pair = Pair.new()
end

  # GET /pairs/1/edit
  def edit
  end

  # POST /pairs
  # POST /pairs.json
  def create
    @pair = Pair.new(pair_params)
	Group.find(@pair.group_id).students.each do |student|
		@miss=@pair.misses.build({:hours => params[:miss][:hours][student.id.to_s],:student_id => student.id})
	
	end
    respond_to do |format|
      if @pair.save
        format.html { redirect_to @pair, notice: 'Pair was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pair }
      else
        format.html { render action: 'new' }
        format.json { render json: @pair.errors, status: :unprocessable_entity }
      end
    end
  end

  def stud
  	@pair.students
  end

  # PATCH/PUT /pairs/1
  # PATCH/PUT /pairs/1.json
  def update
    respond_to do |format|
      if @pair.update(pair_params)
        format.html { redirect_to @pair, notice: 'Pair was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pairs/1
  # DELETE /pairs/1.json
  def destroy
    @pair.destroy
    respond_to do |format|
      format.html { redirect_to pairs_url }
      format.json { head :no_content }
    end
  end

  def choose_subject
	@teacher=Teacher.find(params[:teacher_id])
	@subjects = @teacher.subjects.to_a
  end	

  def choose_group
	@subj=Subject.find(params[:subject_id])
  	@groups = @subj.groups
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pair
      @pair = Pair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pair_params
      params.require(:pair).permit(:group_id,:subject_id,:teacher_id,:number,:auditory,:today)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/misses_helper.rb
module MissesHelper
end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/admin/choose_subject.html.erb
<h2>Выберите предмет:</h2>
<div class="col-sm-4">
    <ul style="list-style: none;" class="list-group">
        <% @subjects.each do |subject| %>
            <li>
	            <%= link_to subject.title ,	
				{:controller => "admin",:action => "choose_group",:subject_id =>subject.id},
				{:class=>"list-group-item btn-link"} %>
			</li>
        <% end %>
    </ul>
</div>

app/views/admin/index.html.erb
<div class="page-header">
<h1>Добро пожаловать, <%= @teacher.name + " " + @teacher.surname %></h1>
</div>
<div class="row">
	<div class="col-sm-4">
		<h2>Ваши группы:</h2>
		<ul style="list-style: none;" class="list-group">
			<% @groups.uniq.each do |group| %>
				<li><h5><%= link_to group.name ,"/groups/#{group.id}",{:class=>"list-group-item btn-link"} %></h5></li>
			<% end %>
		</ul>
	</div>

	<div class="col-sm-4">
		<h2>Ваши предметы:</h2>
		<ul style="list-style: none;" class="list-group">
			<% @subjects.each do |subject| %>
				<li><h5><%= link_to subject.title ,"/subjects/#{subject.id}",{:class=>"list-group-item btn-link"} %></h5></li>
			<% end %>
		</ul>
	</div>
</div>

    <div style="float: left; width: auto;">
	<%= button_to 'Новая пара',{:controller => "pairs",:action => "choose_subject",:teacher_id=>@teacher.id},{:class => "btn btn-warning"} %>
    </div>

    <div style="float: left; width: auto; padding-left: 10px;">
	<%= button_to 'Редактировать профиль',edit_teacher_path(@teacher),{:class => "btn btn-warning",:method => :get} %>
    </div>

	<div style="float: left; width: auto; padding-left: 10px;">
	<%= button_to 'Выйти',logout_path, method: :delete,:class => "btn btn-warning" %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Журнал</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/assets/Book-icon-orange.gif">
</head>
<body>
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
		<div class="navbar-header">
			<%= link_to "Журнал", "/main",:class =>"navbar-brand" %>
		</div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><%= link_to "Предметы",subjects_path %></li>
                <li><%= link_to "Группы",groups_path %></li>
                <li><%= link_to "Студенты",students_path %></li>
                <li><%= link_to "Преподаватели",teachers_path %></li>
            </ul>
            <ul class="nav navbar-nav pull-right">
                <% if session[:teacher_id] %>
                    <li>
                    <%= link_to Teacher.find(session[:teacher_id]).name + " " + Teacher.find(session[:teacher_id]).surname, "/admin/index" %>
                    </li>
                <% else %>
                    <li><%= link_to "Войти",login_path %></li>
                <%end%>
                
            </ul>
        </div>
    </div>
</div>
<br>
<br>
<br>
<div class="container" >
<%= yield %>
</div>
</body>
</html>