config/routes.rb
Journal2::Application.routes.draw do
  get "admin/index"
  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	delete 'logout' => :destroy
  end
  get "sessions/create"
  get "sessions/destroy"
  resources :teachers

  resources :misses

  get "pairs/choose_group"
  get "pairs/choose_subject"
  get "admin/choose_subject"
  get "admin/choose_group"
  post "pairs/choose_group"
  post "pairs/choose_subject" 
  resources :pairs
  get "subjects/student_statistics"

  resources :students

  resources :groups

  resources :subjects
	
  resources :main

  

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :students
	has_many :pairs
	has_and_belongs_to_many :subjects
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index,:show]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @all_subjs=all_subjects
    @summary=@all_subjs.inject(0) { |sum,tuple| sum+=tuple[1]}
    @all_subjs.each do |tuple|
      tuple[1]=Float(tuple[1])/@summary
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
	subj_ids=params[:subject_ids]
	subj_ids.each do |subj_id|
		s=Subject.find(subj_id)
		s.groups << @group
	end
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
	subj_ids=params[:subject_ids]
	@group.subjects.clear
	subj_ids.each do |subj_id|
		s=Subject.find(subj_id)
		s.groups << @group
	end
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  def all_subjects
      @all_subjs = Hash.new
      @group.subjects.each do |subj|
        @all_subjs[subj.title]=0;
      end
      Pair.where("group_id = #{@group.id}").each do |pair|
          @all_subjs[pair.subject.title]+=2
      end
      @all_subjs.sort_by {|k,v| -v}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :course, :number_of_students)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-sm-6">
  <div class="field">
    <h3>Код группы</h3>
    <%= f.text_field :name, :class => "form-control"%>
  </div>
  <label for="sel"><h3>Курс  </h3></label>
  <%= f.select :course, options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6]],1),:id => "sel" %>
  <div>
  <h3>Предметы</h3>
  <div class="checkbox">
	<ul style="list-style: none;">
		<% Subject.all.each do |subject| %>
			<li>
				<%= check_box_tag 'subject_ids[]', subject.id %>
				<h5><%= subject.title %></h5>
			</li>
		<% end %>
	</ul>	
  </div>
</div>
<br>
  <%if @group.new_record? %>
    <div class="actions">
      <%= f.submit "Создать",:class => "btn btn-warning"%>
    </div>
  <%else%>
    <div class="actions">
      <%= f.submit "Изменить",:class => "btn btn-warning"%>
    </div>
  <%end%>
</div>
</div>
<% end %>

app/views/groups/edit.html.erb
<div class="page-header">
	<h1>Изменить группу</h1>
</div>

<%= render 'form' %>

app/views/groups/index.html.erb
<div class="page-header">
	<h1>Список групп</h1>
</div>
<% i = 1 %>
<div class="row">
<% while i < 5 %>
	<%Group.where("course = #{i}").each do |one_group|%>
		<div class="col-sm-4 thumbnail" align="center" >
			<h2><%= "#{i}" + " курс" %> </h2>
			<ul style="list-style: none;" class="list-group">
				<li><h5><%= link_to one_group.name ,one_group,{:class=>"list-group-item btn-link"} %></h5></li>
			</ul>
		</div>
	<% end %>
	<% i+=1 %>
<%end %>
</div>

<% if session[:teacher_id] %>
<%= button_to 'Создать группу', new_group_path,:class => "btn btn-info",:method => :get %>
<%end %>

app/views/groups/new.html.erb
<div class="page-header">
	<h1>Создать группу</h1>
</div>

<%= render 'form' %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
	<h1>Профиль группы</h1>
</div>
<h3>
  <strong>Номер группы:</strong>
  <%= @group.name %>
</h3>

<h3>
  <strong>Курс:</strong>
  <%= @group.course %>
</h3>

<h3>
  <strong>Число студентов:</strong>
  <%= @group.students.count %>
</h3>
<div class="row">
	<div class="col-sm-6">
		<h3><strong>Изучаемые предметы:</strong></h3>
		<ul style="list-style: none;" class="list-group">	
			<% @group.subjects.each do |subj| %>
				<li><h5><%=link_to subj.title,subj,:class => " btn-link list-group-item "%></h5></li>
			<% end %>
		</ul>
	</div>
	<div class="col-sm-6">
		<h3><strong>Студенты:</strong></h3>
		<ul style="list-style: none;" class="list-group">	
			<% Student.where(group: @group).each do |student| %>
				<li><%=link_to student.name + " " +student.surname,student,:class => "btn-link list-group-item"%></li>
			<% end %>
		</ul>
	</div>
</div>

<script type="text/javascript">

$(function () {
    $('#stat').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: 'Процентное соотношение количества часов по предметам'
        },
        tooltip: {
    	    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'От общего числа часов',
            data: <%=raw @all_subjs.to_json%>
        }]
    });
});

</script>
<div class="thumbnail" id="stat" ></div>

<p>
	<%if session[:teacher_id] %>
	 <div style="float: left; width: auto;">
    <%= button_to 'Редактировать', edit_group_path(@group), :class =>"btn btn-warning",:method => :get %>  
    </div>

	<div style="float: left; width: auto; padding-left: 10px;">
    <%= button_to 'Удалить', @group,:class => "btn btn-danger",:method => :delete,data: {confirm: "Вы уверены?"} %>
    </div>
	<% end %>
	<div style="float: left; width: auto; padding-left: 10px;">
    <%= button_to 'Назад', groups_path,:class => "btn btn-info",:method => :get %>
    </div>
	

</p>