config/routes.rb
Journal2::Application.routes.draw do
  get "admin/index"
  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	delete 'logout' => :destroy
  end
  get "sessions/create"
  get "sessions/destroy"
  resources :teachers

  resources :misses

  get "pairs/choose_group"
  get "pairs/choose_subject"
  get "admin/choose_subject"
  get "admin/choose_group"
  post "pairs/choose_group"
  post "pairs/choose_subject" 
  resources :pairs
  get "subjects/student_statistics"

  resources :students

  resources :groups

  resources :subjects
	
  resources :main

  

end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_and_belongs_to_many :groups
	has_many :pairs
	has_and_belongs_to_many :teachers
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  skip_before_action :authorize, only: [ :show, :index,:student_statistics]
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  Misc = Struct.new(:date,:hour)
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)
	teacher_ids=params[:teacher_ids]
	teacher_ids.each do |teacher|
		t=Teacher.find(teacher)
		t.subjects << @subject
	end
    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subject }
      else
        format.html { render action: 'new' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
	teacher_ids=params[:teacher_ids]
	@subject.teachers.clear
	teacher_ids.each do |teacher|
		t=Teacher.find(teacher)
		t.subjects << @subject
	end
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end

  def student_statistics
	@subj=Subject.find(params[:subject_id])
	@stud=Student.find(params[:student_id])
	@pairs=@subj.pairs.where("group_id = #{@stud.group.id}")
	@to_print = Array.new
	@pairs.each do |pair|
		pair.misses.where(" student_id = #{@stud.id}").each do |m|
			@to_print << Misc.new(pair.today,m.hours)
		end
	end
	
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:title, :teacher, :img)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
<div class="col-sm-6">
  <div class="field">
    <h3>Название</h3>
    <%= f.text_field :title,:class => "form-control"%>
  </div>
  <div class="field">
    <h3>Ссылка на изображение</h3>
	<%= f.text_field :img,:class => "form-control" %>
  </div>
  <h3>Преподаватели:</h3>
  <div class="checkbox">
    <ul style="list-style: none;">
        <% Teacher.all.each do |teacher| %>
            <li>
                <%= check_box_tag 'teacher_ids[]', teacher.id %>
                <h5> <%=teacher.name + " " + teacher.patronymic + " " + teacher.surname  %></h5>
				
            </li>
        <% end %>
    </ul>   
  </div>
  <br>
  <%if @subject.new_record? %>
    <div class="actions">
      <%= f.submit "Создать",:class => "btn btn-warning"%>
    </div>
  <%else%>
    <div class="actions">
      <%= f.submit "Изменить",:class => "btn btn-warning"%>
    </div>
  <%end%>
  </div>
</div>
<% end %>

app/views/subjects/edit.html.erb
<div class="page-header">
	<h1>Изменение предмета</h1>
</div>
<%= render 'form' %>

app/views/subjects/index.html.erb
<div class="page-header">
	<h1>Предметы</h1>
</div>
<div class="row">
    <% @subjects.each do |subject| %>
		<div class="col-md-2" align="center">
        	<%= link_to image_tag(subject.img,:class=>"img-responsive")+subject.title,subject,:class=>"thumbnail btn-link" ,:style=>"font-weight:bold;"%>
		</div>
    <% end %>
</div>
<% if session[:teacher_id] %>
<%= button_to 'Создать предмет', new_subject_path,:class=>"btn btn-info",:method=> :get %>
<% end %>

app/views/subjects/new.html.erb
<div class="page-header">
	<h1>Новый предмет</h1>
</div>

<%= render 'form' %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1><%= @subject.title %></h1>
</div>
<div class="row">
	<div class="col-sm-4 ">
		<h3>
		  <strong>Преподаватели:</strong>
		</h3>
		
		<ul style="list-style: none;" class="list-group">
			<% @subject.teachers.each do |teacher| %>
				<li>
					<%= link_to teacher.name + " " + teacher.patronymic + " " + teacher.surname,teacher,:class=> "list-group-item btn-link"%>
				</li>
			<% end %>
		</ul>
	</div>
	<div class="col-sm-4">
		<h3><strong>Изучающие группы:</strong> </h3>
		<ul style="list-style: none;" class="list-group">
			<%@subject.groups.each do |group| %>
				<li><%= link_to group.name,group,:class=>"list-group-item btn-link" %></li>
			<% end %>
		</ul>
	</div>
	<div class="col-sm-4">
	</div>
</div>
<p>
    <% if session[:teacher_id] %>
    <div style="float: left; width: auto;">
    <%= button_to 'Редактировать', edit_subject_path(@subject), :class =>"btn btn-warning",:method => :get %>  
    </div>

    <div style="float: left; width: auto; padding-left: 10px;">
    <%= button_to 'Удалить', @subject,:class => "btn btn-danger",:method => :delete,data: {confirm: "Вы уверены?"} %>
    </div>
    <% end %>
    <div style="float: left; width: auto; padding-left: 10px;">
    <%= button_to 'Назад', subjects_path,:class => "btn btn-info",:method => :get %>
    </div>

</p>

app/views/subjects/student_statistics.html.erb
<div class="container">
<div class="page-header">
	<h3>Статискика студента <%=@stud.name + " " + @stud.surname%> по предмету <%= @subj.title %></h3>
</div>
<div class="col-sm-4">
<table class="table table-striped table-bordered" >	
  <thead>
    <tr>
      <td align="center"><strong>Число</strong></td>
	  <td align="center"><strong>Часов пропущено</strong></td>
    </tr>
  </thead>
  <tbody>
    <% @to_print.each do |dat| %>
      <tr>
        <td width="50%" align="center"><%= dat.date %></td>
        <td width="50%" align="center"><%= dat.hour %></td>
      </tr>
    <% end %>
  </tbody>

</table>
</div>
</div>