config/routes.rb
Journal2::Application.routes.draw do
  get "admin/index"
  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	delete 'logout' => :destroy
  end
  get "sessions/create"
  get "sessions/destroy"
  resources :teachers

  resources :misses

  get "pairs/choose_group"
  get "pairs/choose_subject"
  get "admin/choose_subject"
  get "admin/choose_group"
  post "pairs/choose_group"
  post "pairs/choose_subject" 
  resources :pairs
  get "subjects/student_statistics"

  resources :students

  resources :groups

  resources :subjects
	
  resources :main

  

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	validates :login, presence: true, uniqueness: true
	has_secure_password
	has_and_belongs_to_many :subjects
	has_many :pairs
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:show,:index]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teachers_url, notice: "Teacher #{@teacher.name + " " + @teacher.surname} was successfully created." }
        format.json { render action: 'show', status: :created, location: @teacher }
      else
        format.html { render action: 'new' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teachers_url, notice: "Teacher #{@teacher.name + " " + @teacher.surname} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:degree, :name, :surname,:patronymic,:login,:password,:password_confirmation,:img)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%if @teacher.new_record? %>

<div class="row">
  <div class="col-sm-6">
  <div class="field">
  <h3>Логин</h3>
	<%= f.text_field :login ,:class=>"form-control"%>
  </div>
  <div class="field">
  <h3>Пароль</h3>
	<%= f.password_field :password, size: 40,:class=>"form-control" %>
  </div>
  <div>
  <h3>Подтвердите пароль</h3>
    <%= f.password_field :password_confirmation, size: 40 ,:class=>"form-control"%>
  </div>
  <% end %>
  <div class="field">
    <h3>Имя</h3>
    <%= f.text_field :name, :class => "form-control"%>
  </div>
  <div class="field">
    <h3>Отчество</h3>
    <%= f.text_field :patronymic, :class=>"form-control" %>
  </div>
  <div class="field">
    <h3>Фамилия</h3>
    <%= f.text_field :surname, :class=>"form-control" %>
  </div>
  <div class="field">
    <h3>Научная степень</h3>
    <%= f.text_field :degree, :class=>"form-control" %>
  </div>
  <div class="field">
    <h3>Ссылка на изображение</h3>
	<%= f.text_field :img,:class=>"form-control" %>
  </div>
  <br>
  <%if @teacher.new_record? %>
    <div class="actions">
      <%= f.submit "Создать",:class => "btn btn-warning"%>
    </div>
  <%else%>
    <div class="actions">
      <%= f.submit "Изменить",:class => "btn btn-warning"%>
    </div>
  <%end%>
  </div>
</div>
</div>
<% end %>

app/views/teachers/_update_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :patronymic %><br>
    <%= f.text_field :patronymic %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :degree %><br>
    <%= f.text_field :degree %>
  </div>
  <div class="field">
    <%= f.label :img %><br>
    <%= f.text_field :img %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<div class="page-header">
	<h1>Изменить данные</h1>
</div>
<%= render 'form' %>

app/views/teachers/index.html.erb
<div class="page-header">
    <h1>Преподаватели</h1>
</div>
<div class="row">
    <% @teachers.each do |teacher| %>
        <div class="col-md-2" align="center">
            <%= link_to image_tag(teacher.img,:class=>"img-responsive") + teacher.name + " " + teacher.patronymic + " " + teacher.surname,teacher,:class=>"thumbnail btn-link" ,:style=>"font-weight:bold;"%>
        </div>
    <% end %>
</div>
<% if session[:teacher_id] %>
<%= button_to 'Зарегистрировать преподавателя', new_teacher_path,:method => :get,:class=>"btn btn-info" %>
<% end %>

app/views/teachers/new.html.erb
<div class="page-header">
	<h1>Созать преподавателя</h1>
</div>
<%= render 'form' %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
	<h1>Профиль преподавателя </h1>
</div>
<div class="row">
	<div class="col-sm-6">
		<h3>
		  <strong>Имя:</strong>
		  <%= @teacher.name %>
		</h3>
		<h3>
		  <strong>Отчество:</strong>
		  <%= @teacher.patronymic %>
		</h3>
		
		<h3>
		  <strong>Фамилия:</strong>
		  <%= @teacher.surname %>
		</h3>
		<h3>
		  <strong>Научная степень:</strong>
		  <%= @teacher.degree %>
		</h3>
	</div>
	<div class="col-sm-4 thumbnail">
		<%= image_tag(@teacher.img,:class=>"img-responsive") %>
	</div> 
</div>

<% if session[:teacher_id] == @teacher.id %>

    <div style="float: left; width: auto;">
    <%= button_to 'Перейти в личный кабинет', "/admin/index", :class =>"btn btn-success",:method => :get %>  
    </div>

    <div style="float: left; width: auto; padding-left: 10px;">
    <%= button_to 'Редактировать', edit_teacher_path(@teacher), :class =>"btn btn-warning",:method => :get %>  
    </div>

    <div style="float: left; width: auto; padding-left: 10px;">
    <%= button_to 'Удалить', @teacher,:class => "btn btn-danger",:method => :delete,data: {confirm: "Вы уверены?"} %>
    </div>
    <% end %>
    <div style="float: left; width: auto; padding-left: 10px;">
    <%= button_to 'Назад', teachers_path,:class => "btn btn-info",:method => :get %>
    </div>

</p>